@host = http://localhost

POST {{host}}:8000/user/signup
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "companyName": "Vividly",
    "email": "test512@gmail.com",
    "password": 123456789,
    "confirmPassword": 123456789,
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

POST {{host}}:8000/user/login
Content-Type: application/json

{
    "email": "mohamed.medhat2199@gmail.com",
    "password": 123456789,
    "registrationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTk5YmViYi03ZDk1LTRmYWUtYTU3ZC1hNTU2ODY3ZTA3ZDUiLCJpYXQiOjE2NDUzMDc4ODUsImV4cCI6MTY0NTM0Mzg4NX0.lfdATDlZJI8vAlrkiaiCCfa9R4z1mpPMmnEXD3Tp_TE"
}

###

POST {{host}}:8000/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDY0ODYxNzIsImV4cCI6MTY0NjUyMjE3Mn0.68xmKpnvlp7kCzkW7UAvoEG9Vz2xcl5rphVyZVOV1rE
Content-Type: application/json

{
    "registrationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTk5YmViYi03ZDk1LTRmYWUtYTU3ZC1hNTU2ODY3ZTA3ZDUiLCJpYXQiOjE2NDUzMDc4ODUsImV4cCI6MTY0NTM0Mzg4NX0.lfdATDlZJI8vAlrkiaiCCfa9R4z1mpPMmnEXD3Tp_TE"
}
###

POST {{host}}:8000/user/confirm-email
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MjBhYzNkNC04Zjc0LTRhN2EtYmI4OC1lODM1M2Y5YTZlNDEiLCJpYXQiOjE2NDYzMzMxOTIsImV4cCI6MTY0NjM2OTE5Mn0.H6BWVjJaIJEnEi61W1NQg56vcX0s4RJ902oEqmPg7RY

###

POST {{host}}:8000/user/verify
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MjBhYzNkNC04Zjc0LTRhN2EtYmI4OC1lODM1M2Y5YTZlNDEiLCJpYXQiOjE2NDYzMzMxOTIsImV4cCI6MTY0NjM2OTE5Mn0.H6BWVjJaIJEnEi61W1NQg56vcX0s4RJ902oEqmPg7RY
Content-Type: application/json

{
    "verificationCode": "77ST87AT"
}


###

GET {{host}}:8001/user/ead5720b-4c3f-4657-9060-d7fc5941498f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

PUT {{host}}:8001/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json

{
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

PUT {{host}}:8001/user/changepassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json

{
    "oldPassword": "1234567890",
    "newPassword": "123456789",
    "newConfirmPassword": "123456789"
}

###

GET {{host}}:8001/user/notifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

Post {{host}}:8001/user/read-notification/7c809232-715a-4fce-9596-5f62fc654736
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

POST {{host}}:8001/job-listing/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json

{
    "positionName": "Job E",
    "expiryDate": "2022-03-28",
    "questions":[
        {
            "statement": "Question 1.1",
            "keywords": ["aab", "bba", "cca"],
            "timeToThink": 3,
            "timeToAnswer": 5
        },
        {
            "statement": "Question 1.2",
            "keywords": ["dda", "eea", "ffa"],
            "timeToThink": 7,
            "timeToAnswer": 15
        }
    ]
}

###

GET {{host}}:8001/job-listing/get-listings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcyNjk1OTYsImV4cCI6MTY0NzMwNTU5Nn0.YLm3Z7A3v8zBy28HwOv5DOBy8CqrOUJU3p6CJZIO5LU

###

GET {{host}}:8001/job-listing/ce2abdd9-f73f-4a3e-a09a-06cddce82cce
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

POST {{host}}:8001/job-listing/invite
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json

{
    "listingId": "15dd2277-edfb-4492-ae0b-d279e0e294db",
    "candidates": [
        {
            "name": "Mohamed Medhat",
            "email": "mohamed.medhat2199@gmail.com",
            "phoneCode": "+20",
            "phoneNumber": 1155282790
        },
        {
            "name": "3M Medo",
            "email": "test@test.com",
            "phoneCode": "+20",
            "phoneNumber": 1155282790
        }
    ]
}

###

GET {{host}}:8002/candidate/join/09ED80H9
Content-Type: application/json

###

POST {{host}}:8002/candidate/upload-video
Content-Type: application/json

{
    "interviewId": "74b74292-3642-486a-8319-255bb7e7da5a",
    "questionId": "c0cb024f-609e-439e-85b8-6cb4f8172b99",
    "video": "https://www.youtube.com/watch?v=0g1Q4fBDp2U",
    "lastVideo": false
}

###

POST {{host}}:8002/candidate/upload-video
Content-Type: application/json

{
    "interviewId": "74b74292-3642-486a-8319-255bb7e7da5a",
    "questionId": "db8c8b04-4bea-44d7-b378-070ad040b3f5",
    "video": "https://www.youtube.com/watch?v=0g1Q4fBDp2U",
    "lastVideo": true
}

###

GET {{host}}:8001/job-listing/answers/74b74292-3642-486a-8319-255bb7e7da5a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json