@host = http://localhost

POST {{host}}:8000/user/signup
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "companyName": "Vividly",
    "email": "test512@gmail.com",
    "password": 123456789,
    "confirmPassword": 123456789,
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

POST {{host}}:8000/user/login
Content-Type: application/json

{
    "email": "mohamed.medhat2199@gmail.com",
    "password": 123456789
}

###

POST {{host}}:8000/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYjQ3NjY5NC0xZjVmLTQ3YmEtYjBmNy02YmVjZjg2MDBjODciLCJpYXQiOjE2NTI4MTgxNTMsImV4cCI6MTY1Mjg1NDE1M30.pGgiu4ovmJPYyk4FNLd4o5S0yNaMAwpfMLPLdfJYJ-A
Content-Type: application/json

###

POST {{host}}:8000/user/confirm-email
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MjYzZTk1Mi1mYTdhLTQ3Y2MtYTJmZC02ZDM2YWVlYjgyM2IiLCJpYXQiOjE2NDgyMjk0MjEsImV4cCI6MTY0ODI2NTQyMX0.z_LzQE41QYNJ7Kfcf3Q18yg0Qn-y8FEGOXTCefpWpnc

###

POST {{host}}:8000/user/verify
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MjBhYzNkNC04Zjc0LTRhN2EtYmI4OC1lODM1M2Y5YTZlNDEiLCJpYXQiOjE2NDYzMzMxOTIsImV4cCI6MTY0NjM2OTE5Mn0.H6BWVjJaIJEnEi61W1NQg56vcX0s4RJ902oEqmPg7RY
Content-Type: application/json

{
    "verificationCode": "77ST87AT"
}


###

GET {{host}}:8001/user/ead5720b-4c3f-4657-9060-d7fc5941498f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

PUT {{host}}:8001/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json

{
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

PUT {{host}}:8001/user/changepassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w
Content-Type: application/json

{
    "oldPassword": "1234567890",
    "newPassword": "123456789",
    "newConfirmPassword": "123456789"
}

###

GET {{host}}:8001/user/notifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

Post {{host}}:8001/user/read-notification/7c809232-715a-4fce-9596-5f62fc654736
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDcxMTA3OTIsImV4cCI6MTY0NzE0Njc5Mn0.DD7oXezpu3wHgiCI2I4eL02JftYzIYL7Po3zcG50C_w

###

POST {{host}}:8001/job-listing/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NTAxNTM1ODQsImV4cCI6MTY1MDE4OTU4NH0.rDCDVqC2Hq8V_cPdfl2E-HVM8rHj4KAxRq0LBexk2-I
Content-Type: application/json

{
    "positionName": "Job FFFFFFFFFF",
    "expiryDate": "2022-04-28",
    "questions":[
        {
            "statement": "Question 1.1",
            "keywords": ["aab", "bba", "cca"],
            "timeToThink": 3,
            "timeToAnswer": 5
        },
        {
            "statement": "Question 1.2",
            "keywords": ["dda", "eea", "ffa"],
            "timeToThink": 7,
            "timeToAnswer": 15
        }
    ]
}

###

GET {{host}}:8001/job-listing/get-listings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYjQ3NjY5NC0xZjVmLTQ3YmEtYjBmNy02YmVjZjg2MDBjODciLCJpYXQiOjE2NTI4MTgwNTYsImV4cCI6MTY4NDM3NTY1Nn0.TAgIpfcjM5YQJ2cfSrRfHtQsWULYfaDMARijz6ZCRew

###

GET {{host}}:8001/job-listing/ce2abdd9-f73f-4a3e-a09a-06cddce82cce
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDgyMDQzODgsImV4cCI6MTY0ODI0MDM4OH0.RtRsb2HrFUZN3H4MOLC8gJk4YzRHdDWIrkIh0gKne4c

###

DELETE  {{host}}:8001/job-listing/3b04e37e-c28d-4862-a042-f362739c9ca1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYjQ3NjY5NC0xZjVmLTQ3YmEtYjBmNy02YmVjZjg2MDBjODciLCJpYXQiOjE2NTI4MTgwNTYsImV4cCI6MTY4NDM3NTY1Nn0.TAgIpfcjM5YQJ2cfSrRfHtQsWULYfaDMARijz6ZCRew

###

POST {{host}}:8001/job-listing/invite
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NTAxNTM1ODQsImV4cCI6MTY1MDE4OTU4NH0.rDCDVqC2Hq8V_cPdfl2E-HVM8rHj4KAxRq0LBexk2-I
Content-Type: application/json

{
    "listingId": "ef0d7b7c-bb86-4229-970a-32e85f05d0f3",
    "candidates": [
        {
            "name": "Mohamed Medhat",
            "email": "mohamed.medhat2199@gmail.com",
            "phoneCode": "+20",
            "phoneNumber": 1155282790
        },
        {
            "name": "3M Medo",
            "email": "test@test.com",
            "phoneCode": "+20",
            "phoneNumber": 1155282790
        }
    ]
}

###

GET {{host}}:8002/candidate/join/70TA07H2
Content-Type: application/json

###

POST {{host}}:8002/candidate/upload-video
Content-Type: application/json

{
    "interviewId": "94f88c0a-fb67-48d7-9787-859ba0413e89",
    "questionId": "bc361b7b-f240-428a-99c4-6842c170b0bf",
    "video": [0,0,0,0,0,0],
    "lastVideo": true,
    "videoExtension": "webm"
}

###

POST http://3.145.131.124/api/interviewee/candidate/upload-video
Content-Type: application/json

{
    "interviewId": "e1833e77-f73f-49c6-9288-2b01082542a2",
    "questionId": "2022-03-06 00:09:05.783902",
    "video": [0,0,0,0,0,0],
    "lastVideo": true,
    "videoExtension": "webm"
}

###
GET {{host}}:8001/job-listing/answers/94f88c0a-fb67-48d7-9787-859ba0413e89
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDkzNzEyNjMsImV4cCI6MTY0OTQwNzI2M30.YJpOA5z8VorfdUt0tT-3vDG8z5XNZJzKTyw7q_gIQ0Y
Content-Type: application/json

###
POST {{host}}:8001/job-listing/evaluate/94f88c0a-fb67-48d7-9787-859ba0413e89
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDgyMDQzODgsImV4cCI6MTY0ODI0MDM4OH0.RtRsb2HrFUZN3H4MOLC8gJk4YzRHdDWIrkIh0gKne4c
Content-Type: application/json

{
    "evaluations": [
        {
            "questionId": "bc361b7b-f240-428a-99c4-6842c170b0bf",
            "evaluation": 100
        }
    ]
}

###
GET {{host}}:8001/job-listing/candidates/ce2abdd9-f73f-4a3e-a09a-06cddce82cce
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYWQ1NzIwYi00YzNmLTQ2NTctOTA2MC1kN2ZjNTk0MTQ5OGYiLCJpYXQiOjE2NDk1OTQyMzUsImV4cCI6MTY0OTYzMDIzNX0.iOQv_ELEkrQaDYbeySoTejckOBjHz0wwIhAiWtQNRZY
