@host = http://localhost:8080

POST {{host}}/user/signup
Content-Type: application/json

{
    "firstName": "Mohamed",
    "lastName": "Medhat",
    "companyName": "Vividly",
    "email": "mohamed.medhat2199@gmail.com",
    "password": 123456789,
    "confirmPassword": 123456789,
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

POST {{host}}/user/confirm-email
Content-Type: application/json

{
    "userId": "de6b8de4-412d-4a5b-ae34-3203788660da"
}

###

POST {{host}}/user/verify
Content-Type: application/json

{
    "userId": "de6b8de4-412d-4a5b-ae34-3203788660da",
    "verificationCode": "76YH762H"
}

###

POST {{host}}/user/login
Content-Type: application/json

{
    "email": "mohamed.medhat2199@gmail.com",
    "password": 123456789
}

###

GET {{host}}/user/de6b8de4-412d-4a5b-ae34-3203788660da
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NTRjY2VmNC0wNGEzLTQwYTEtOTlhNi0yMDU4MDA0ZmJjOTIiLCJpYXQiOjE2NDAwMDkwMjcsImV4cCI6MTY0MDA0NTAyN30.loGv3NA9lF52rCkIkjF8L0p4mFWgL7Jjn4uzlAF1lnI

###

PUT {{host}}/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2Mzk4NDYxNzUsImV4cCI6MTYzOTg4MjE3NX0.xjlSnPP425aZTPLhNGig-oxln7p8s2wNsu2YDC7B21c
Content-Type: application/json

{
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

PUT {{host}}/user/changepassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2Mzk5MjAxNDksImV4cCI6MTYzOTk1NjE0OX0.uDvacTw34WhvPoRmwDk4bS7zcmZ3t5_rzdvtpMhyvHs
Content-Type: application/json

{
    "oldPassword": 111111111,
    "newPassword": 123456789,
    "newConfirmPassword": 123456789
}

###

POST {{host}}/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2MzkzMTE2NTksImV4cCI6MTYzOTM0NzY1OX0.cF2H3OPFsdbV8i3flEWpjGpQcltiEb5O_Xm7wnzYox0


###

POST {{host}}/job-listing/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZTZiOGRlNC00MTJkLTRhNWItYWUzNC0zMjAzNzg4NjYwZGEiLCJpYXQiOjE2NDAwMDk1NDgsImV4cCI6MTY0MDA0NTU0OH0.tc1Tr8flNW6pnqM_23X6YQPk_IirYPvNFeo3FhWZMIA
Content-Type: application/json

{
    "positionName": "Test2",
    "expiryDate": "2022-01-31",
    "questions":[
        {
            "statement": "aa",
            "keywords": ["aaa", "bbb", "ccc"],
            "timeToThink": 3,
            "timeToAnswer": 5
        },
        {
            "statement": "bb",
            "keywords": ["ddd", "eee", "fff"],
            "timeToThink": 7,
            "timeToAnswer": 15
        }
    ]
}

###

GET {{host}}/job-listing/get-listings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZTZiOGRlNC00MTJkLTRhNWItYWUzNC0zMjAzNzg4NjYwZGEiLCJpYXQiOjE2NDAwODk0NzMsImV4cCI6MTY0MDEyNTQ3M30.pmM-iUMVLRM3Jn_zVKpTKry4K96kv7Eo7_sWdJyVjF8

###

GET {{host}}/job-listing/e3692887-872d-4ff2-9220-862f25ea771c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZTZiOGRlNC00MTJkLTRhNWItYWUzNC0zMjAzNzg4NjYwZGEiLCJpYXQiOjE2NDAwODk0NzMsImV4cCI6MTY0MDEyNTQ3M30.pmM-iUMVLRM3Jn_zVKpTKry4K96kv7Eo7_sWdJyVjF8


###

POST {{host}}/job-listing/invite
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZTZiOGRlNC00MTJkLTRhNWItYWUzNC0zMjAzNzg4NjYwZGEiLCJpYXQiOjE2NDQ2ODc5MzgsImV4cCI6MTY0NDcyMzkzOH0.hBWBAKbQLVUuehaPyCrUfjKop-YKeOKDyPsX3guYinw
Content-Type: application/json

{
    "listingId": "e3692887-872d-4ff2-9220-862f25ea771c",
    "candidates": [
        {
            "name": "Mohamed Medhat",
            "email": "mohamed.medhat2199@gmail.com",
            "phoneCode": "+20",
            "phoneNumber": 1155282790
        },
        {
            "name": "3M Medo",
            "email": "test@test.com",
            "phoneCode": "+20",
            "phoneNumber": 1155282790
        }
    ]
}