@host = http://localhost:8080

POST {{host}}/user/signup
Content-Type: application/json

{
    "firstName": "Mohamed",
    "lastName": "Medhat",
    "companyName": "Vividly",
    "email": "Test@vividly.com",
    "password": 123456789,
    "confirmPassword": 123456789,
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

POST {{host}}/user/confirm-email
Content-Type: application/json

{
    "userId": "302b1fc4-04af-4f77-bd23-f85228d51328"
}

###

POST {{host}}/user/verify
Content-Type: application/json

{
    "userId": "302b1fc4-04af-4f77-bd23-f85228d51328",
    "verificationCode": "96HE98MG"
}

###

POST {{host}}/user/login
Content-Type: application/json

{
    "email": "mohamed.medhat2199@gmail.com",
    "password": 123456789
}

###

GET {{host}}/user/302b1fc4-04af-4f77-bd23-f85228d51328
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2MzkzMTE2NTksImV4cCI6MTYzOTM0NzY1OX0.cF2H3OPFsdbV8i3flEWpjGpQcltiEb5O_Xm7wnzYox0

###

PUT {{host}}/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2MzkzMTE2NTksImV4cCI6MTYzOTM0NzY1OX0.cF2H3OPFsdbV8i3flEWpjGpQcltiEb5O_Xm7wnzYox0
Content-Type: application/json

{
    "companyName": "Vividly",
    "phoneCode": "+20",
    "phoneNumber": 1155282790
}

###

PUT {{host}}/user/changepassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2MzkzMTE2NTksImV4cCI6MTYzOTM0NzY1OX0.cF2H3OPFsdbV8i3flEWpjGpQcltiEb5O_Xm7wnzYox0
Content-Type: application/json

{
    "oldPassword": 111111111,
    "newPassword": 123456789,
    "newConfirmPassword": 123456789
}

###

POST {{host}}/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2MzkzMTE2NTksImV4cCI6MTYzOTM0NzY1OX0.cF2H3OPFsdbV8i3flEWpjGpQcltiEb5O_Xm7wnzYox0


###

POST {{host}}/job-listing/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMDJiMWZjNC0wNGFmLTRmNzctYmQyMy1mODUyMjhkNTEzMjgiLCJpYXQiOjE2Mzk2NTc5NjcsImV4cCI6MTYzOTY5Mzk2N30.W6Tej7d3YE0R7JcarxwiwQbA2qmdxoGoAjKfCZc2yKc
Content-Type: application/json

{
    "positionName": "Test3",
    "expiryDate": "2022-01-31",
    "questions":[
        {
            "statement": "a",
            "keywords": ["aaa", "bba", "cca"],
            "timeToThink": 2,
            "timeToAnswer": 4
        },
        {
            "statement": "b",
            "keywords": ["dda", "eea", "ffa"],
            "timeToThink": 6,
            "timeToAnswer": 12
        }
    ]
}