# for GUI ==> https://app.swaggerhub.com/apis/mohamed.medhat2199/Vividly/1.0.0
openapi: 3.0.0
info:
  description: This is a simple documentation for our backend APIs
  version: '1.0.0'
  title: Vividly
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mohamed.medhat2199/Vividly/1.0.0
  - url: http://localhost:8080
    description: This is the local development server
  - url: https://vividly-api.herokuapp.com/
    description: This is the remote development server
paths:
  /user/signup:
    post:
      summary: Signup for the interviewer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                companyName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
                phoneCode:
                  type: string
                phoneNumber:
                  type: string
      responses:
        '201':
          description: A new user is created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      companyName:
                        type: string
                      email:
                        type: string
                      phoneCode:
                        type: string
                      phoneNumber:
                        type: string
                      loggedIn:
                        type: boolean
                      emailConfirmed:
                        type: boolean
        '422':
          description: Input validation faild.
        '500':
          description: Server side error.
  /user/confirm-email:
    post:
      summary: Send Email confirmation to the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Email confirmation has been sent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: User not found.
        '500':
          description: Server side error.
  /user/verify/:
    post:
      summary: Confirm user's email in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                verificationCode:
                  type: string
      responses:
        '200':
          description: User's email has been confirmed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Authentecation faild.
        '404':
          description: User not found.
        '500':
          description: Server side error.
  /user/login:
    post:
      summary: Login for an interviewer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Loggedin.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      companyName:
                        type: string
                      email:
                        type: string
                      phoneCode:
                        type: string
                      phoneNumber:
                        type: string
                      loggedIn:
                        type: boolean
                      emailConfirmed:
                        type: boolean
                  token:
                    type: string
                  tokenExpireDate:
                    format: date-time
        '404':
          description: User not found.
        '401':
          description: Authentecation faild.
        '500':
          description: Server side error.
  /user/logout:
    post:
      summary: Logout for an interviewer.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      responses:
        '200':
          description: Loggedout.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Authentecation faild.
        '500':
          description: Server side error.
  /user/{user_id}:
    get:
      summary: Get an interviewer info.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The userId of the target user.
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string

      responses:
        '200':
          description: Get the information successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      companyName:
                        type: string
                      email:
                        type: string
                      phoneCode:
                        type: string
                      phoneNumber:
                        type: string
                      loggedIn:
                        type: boolean
                      emailConfirmed:
                        type: boolean
        '401':
          description: Authentecation faild.
        '404':
          description: User not found.
        '500':
          description: Server side error.

  /user/edit:
    put:
      summary: Edit profile for an interviewer.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneCode:
                  type: string
                phoneNumber:
                  type: string
      responses:
        '200':
          description: Profile has been edited.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
                      companyName:
                        type: string
                      email:
                        type: string
                      phoneCode:
                        type: string
                      phoneNumber:
                        type: string
                      loggedIn:
                        type: boolean
                      emailConfirmed:
                        type: boolean
        '401':
          description: Authentecation faild.
        '404':
          description: User not found.
        '500':
          description: Server side error

  /user/changepassword:
    put:
      summary: Change password for an interviewer.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
                newConfirmPassword:
                  type: string
      responses:
        '200':
          description: Password has been changed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Authentecation faild.
        '404':
          description: User not found.
        '500':
          description: Server side error.

  /job-listing/create:
    post:
      summary: Create a job listing.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                positionName:
                  type: string
                expiryDate:
                  format: date-time
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      questionId:
                        type: string
                      jobListingId:
                        type: string
                      statement:
                        type: string
                      timeToThink:
                        type: integer
                      timeToAnswer:
                        type: integer
                      keywords:
                        type: array
                        items:
                          type: string
      responses:
        '200':
          description: Job listing has been created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobListingId:
                    type: string
                  userId:
                    type: string
                  positionName:
                    type: string
                  expiryDate:
                    format: date-time
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        questionId:
                          type: string
                        statement:
                          type: string
                        timeToThink:
                          type: integer
                        timeToAnswer:
                          type: integer
                        keywords:
                          type: array
                          items:
                            type: string

        '401':
          description: Authentecation faild or unconfirmed email.
        '422':
          description: Validation error.
        '500':
          description: Server side error.

  /job-listing/get-listings:
    get:
      summary: get user's job listings.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      responses:
        '200':
          description: get all the user's listings.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobListings:
                    type: array
                    items:
                      type: object
                      properties:
                        jobListingId:
                          type: string
                        userId:
                          type: string
                        positionName:
                          type: string
                        expiryDate:
                          format: date-time
                        invitationsNumber:
                          type: integer
                        interviewsNumber:
                          type: integer
        '401':
          description: Authentecation faild or unconfirmed email.
        '422':
          description: Validation error.
        '500':
          description: Server side error.
  /job-listing/{listing_id}:
    get:
      summary: get the information of a single listing.
      parameters:
        - name: listing_id
          in: path
          required: true
          description: The id of the target listing.
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      responses:
        '200':
          description: get the listing info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobListingId:
                    type: string
                  userId:
                    type: string
                  positionName:
                    type: string
                  expiryDate:
                    format: date-time
                  invitationsNumber:
                    type: integer
                  interviewsNumber:
                    type: integer
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        questionId:
                          type: string
                        jobListingId:
                          type: string
                        statement:
                          type: string
                        timeToThink:
                          type: integer
                        timeToAnswer:
                          type: integer
                        keywords:
                          type: array
                          items:
                            type: string

        '401':
          description: Authentecation faild or unconfirmed email.
        '422':
          description: Validation error.
        '500':
          description: Server side error.

  /job-listing/invite:
    post:
      summary: Invite candidates to an interview.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: jwt of the loggedin user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                listingId:
                  type: string
                candidates:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      phoneCode:
                        type: string
                      phoneNumber:
                        type: string

      responses:
        '200':
          description: Job listing has been created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Authentecation faild or unconfirmed email.
        '404':
          description: Listing not found.
        '422':
          description: Validation error.
        '500':
          description: Server side error.
