name: Github Prettier
on: [push]
jobs:
  prettier:
    name: Check for format problems
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actionsx/prettier@v2
        name: Runs Prettier CLI command
        with:
          args: --check .
